CREATE TABLE IF NOT EXISTS cliente (
  id INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
  NOME VARCHAR(50),
  PLANO BOOLEAN,
  SALDO DECIMAL(10,2),
  CONTA VARCHAR(20),
  DATA_DE_NASCIMENTO DATE
);

CREATE TABLE IF NOT EXISTS transacoes (
  id_transacao INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
  CLIENTE_ID INT NOT NULL,
  TIPO_TRANSACAO VARCHAR(10),
  VALOR DECIMAL(10,2),
  DATA_TRANSACAO DATE,
  FOREIGN KEY (CLIENTE_ID) REFERENCES cliente(id)
);